In [4]:
import numpy as np
print(np.__version__)

1.26.0


====

In [3]:
# Task: Create an array filled with a single value (55)
a = np.full((3,3), 55)
print(a)

[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [4]:
# Task: Create a null vector of size 10 but the fifth value which is 1 
a1 = np.zeros(10)
a1[4] = 1
print(a1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
# Task: Reverse a vector (first element becomes last)
a2 = np.arange(9,-1,-1) 
print(a2)

[9 8 7 6 5 4 3 2 1 0]


In [6]:
# Task: Create a 3x3 matrix with values ranging from 0 to 8 
a3 = np.arange(0,9)
print(a3.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Create a 5x5 matrix with row values ranging from 0 to 4 
a = np.zeros([5,5])
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [34]:
#Create a 3D array with zeros along the second axis
a0 = np.full(4,0)
a2 = np.full(4,2)

arr = np.vstack((a0,a2,a0))

result = np.array([arr,arr])

print(result)

[[[0 0 0 0]
  [2 2 2 2]
  [0 0 0 0]]

 [[0 0 0 0]
  [2 2 2 2]
  [0 0 0 0]]]


In [7]:
    #How to print the following pattern of nxn using NumPy?


a0 = np.eye(8,k=1)
a3 = np.eye(8, k=3)
a5 = np.eye(8, k=5)
a7 = np.eye(8, k=7)

b0 = np.eye(8,k=-1)
b3 = np.eye(8,k=-3)
b5 = np.eye(8,k=-5)
b7 = np.eye(8,k=-7)
arr = a0+a3+a5+a7+b0+b3+b5+b7

for x in arr:
    for y in x:
        print(y)
   print("\n")    
  

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 18)

In [97]:
#Given the following two arrays, add them
array = np.array([
    [3, 2, 8],
    [4, 12, 34],
    [23, 12, 67]
])

newRow = np.array([2, 1, 8])

result = np.vstack((array,newRow))

print(result)

[[ 3  2  8]
 [ 4 12 34]
 [23 12 67]
 [ 2  1  8]]


In [50]:
#Given the following arrays, calculate ((A+B)*(-A/2))

A = np.ones(3)*1
B = np.ones(3)*2

P1 = np.add(A,B)
P2 = np.divide(np.negative(A),2)

result = np.multiply(P1,P2)

result

array([-1.5, -1.5, -1.5])

In [98]:
# Calculate mean of each row of the list

list = [
    np.array([3, 2, 8, 9]),			#5.5
    np.array([4, 12, 34, 25, 78]),		#30.6
    np.array([23, 12, 67])			#34.0
]

print("row1: %0.1f, row2: %0.1f, row3: %0.1f"
      %(np.mean(list[0]), np.mean(list[1]), np.mean(list[2])))

row1: 5.5, row2: 30.6, row3: 34.0


In [21]:
arr1 = np.array([0,1,0,1,0,1,0,1])
arr2 = np.array([1,0,1,0,1,0,1,0])
for n in range(4):
    for x in arr1:
        print (x, end=' ')
    print("\t")
    for x in arr2:
        print(x, end=' ')
    print("\t")


0 1 0 1 0 1 0 1 	
1 0 1 0 1 0 1 0 	
0 1 0 1 0 1 0 1 	
1 0 1 0 1 0 1 0 	
0 1 0 1 0 1 0 1 	
1 0 1 0 1 0 1 0 	
0 1 0 1 0 1 0 1 	
1 0 1 0 1 0 1 0 	
